# Generated by Django 6.0.4 on 2026-04-24 00:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("is_superuser", models.BooleanField(default=False, help_text="Designates that this user has all permissions without explicitly assigning them.", verbose_name="superuser status")),
                ("username", models.CharField(error_messages={"unique": "A user with that username already exists."}, help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.", max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name="username")),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                ("is_staff", models.BooleanField(default=False, help_text="Designates whether the user can log into this admin site.", verbose_name="staff status")),
                ("is_active", models.BooleanField(default=True, help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.", verbose_name="active")),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("phone_num", models.CharField(max_length=20, unique=True)),
                ("groups", models.ManyToManyField(blank=True, help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.", related_name="user_set", related_query_name="user", to="auth.group", verbose_name="groups")),
                ("user_permissions", models.ManyToManyField(blank=True, help_text="Specific permissions for this user.", related_name="user_set", related_query_name="user", to="auth.permission", verbose_name="user permissions")),
            ],
            options={"verbose_name": "user", "verbose_name_plural": "users", "abstract": False},
            managers=[("objects", django.contrib.auth.models.UserManager())],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("passport_id", models.CharField(max_length=50, unique=True)),
                ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="account", to="app.user")),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("card_id", models.CharField(max_length=16, unique=True)),
                ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("cart_name", models.CharField(choices=[("visa", "visa"), ("credit", "credit"), ("master", "master"), ("simple", "simple")], max_length=20)),
                ("cvv", models.CharField(editable=False, max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expair", models.DateField(blank=True, null=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cards", to="app.account")),
            ],
        ),
        migrations.CreateModel(
            name="TransactionInside",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("phone_num", "phone_num"), ("card", "card")], max_length=20)),
                ("sender", models.CharField(max_length=32)),
                ("reciver", models.CharField(max_length=32)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cuur_balance_sender", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("cuur_balance_reciver", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("pending", "pending"), ("success", "success"), ("failed", "failed")], default="success", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("phone_num", "phone_num"), ("card", "card")], max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cuur_balance_sender", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("cuur_balance_reciver", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("pending", "pending"), ("success", "success"), ("failed", "failed")], default="success", max_length=20)),
                ("reciver", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="received_transactions", to="app.account")),
                ("sender", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sent_transactions", to="app.account")),
            ],
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("procent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("status", models.CharField(choices=[("pending", "pending"), ("success", "success"), ("failed", "failed")], default="success", max_length=20)),
                ("card", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deposits", to="app.card")),
            ],
        ),
        migrations.CreateModel(
            name="Credit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("procent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("status", models.CharField(choices=[("pending", "pending"), ("success", "success"), ("failed", "failed")], default="success", max_length=20)),
                ("card", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="credits", to="app.card")),
            ],
        ),
        migrations.CreateModel(
            name="CardBlackList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                ("card", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="blacklist_entry", to="app.card")),
            ],
        ),
        migrations.CreateModel(
            name="AccountBlackList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                ("account", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="blacklist_entry", to="app.account")),
            ],
        ),
    ]
